reportmaker:
  container_name: reportmaker
  labels:
    - "reportmaker-description= Report Generator (xlsx)"
  build: .
  ports:
    - "8000:8000"
  links:
    - code
  command: gunicorn -b 0.0.0.0:8000 manage:reportmaker.app
  # command: ping localhost
  volumes_from: 
    - code


code:
  labels:
    - "reportmaker-code-description= Code of Reportmaker"
  image: busybox
  volumes:
    - ../.:/var/www/html/reportmaker
  command: tail -f /dev/null
  
